In [5]:
import numpy as np
from kalman_filter import KalmanFilter
k = KalmanFilter()
mean_pos = np.array([5,8,0.5,6])
mean_vel = np.zeros_like(mean_pos)
mean = np.r_[mean_pos, mean_vel]
mean1 = np.dot( mean, k._motion_mat.T )

print(mean_vel)
print(mean)
print(mean1)

[0. 0. 0. 0.]
[5.  8.  0.5 6.  0.  0.  0.  0. ]
[5.  8.  0.5 6.  0.  0.  0.  0. ]


In [12]:

measurements = np.array([5,8,6,2,1,0,2,3])
mean = np.array([9,8,8,8])
a = np.random.randint(10, size=(1,8))
print(a)
# d = measurements - mean



[[7 3 5 7 3 6 8 3]]


In [2]:
import torch.nn.functional as F 
import torch
import torch.nn as nn
import numpy as np

a = np.array([[5,3,4,6,8],
              [1,2,6,1,5],
              [8,9,3,0,3]],dtype=np.float32)
a = np.random.randint(10,size=(8,8)).astype(np.float32)
id_feature = torch.tensor([[a]])
print(id_feature)


kernel = 3
pad = (kernel - 1) // 2
hmax = nn.functional.max_pool2d(id_feature, (kernel, kernel), stride=1, padding=pad)
keep = (hmax == id_feature)

print(hmax)
print(keep)
print(id_feature * keep)


# id_feature = F.normalize(id_feature, dim=1)
# print(id_feature)

C:\Users\admin\.conda\envs\pytorch17\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\admin\.conda\envs\pytorch17\lib\site-packages\numpy\.libs\libopenblas.GK7GX5KEQ4F6UYO3P26ULGBQYHGQO7J4.gfortran-win_amd64.dll
C:\Users\admin\.conda\envs\pytorch17\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


tensor([[[[4., 1., 2., 6., 4., 9., 7., 4.],
          [7., 2., 9., 3., 7., 7., 0., 0.],
          [5., 4., 2., 9., 9., 4., 1., 6.],
          [7., 6., 2., 5., 4., 1., 2., 4.],
          [0., 8., 9., 5., 3., 8., 2., 5.],
          [7., 8., 7., 9., 1., 7., 3., 9.],
          [3., 0., 7., 1., 1., 4., 9., 9.],
          [2., 5., 9., 3., 7., 6., 3., 8.]]]])
tensor([[[[7., 9., 9., 9., 9., 9., 9., 7.],
          [7., 9., 9., 9., 9., 9., 9., 7.],
          [7., 9., 9., 9., 9., 9., 7., 6.],
          [8., 9., 9., 9., 9., 9., 8., 6.],
          [8., 9., 9., 9., 9., 8., 9., 9.],
          [8., 9., 9., 9., 9., 9., 9., 9.],
          [8., 9., 9., 9., 9., 9., 9., 9.],
          [5., 9., 9., 9., 7., 9., 9., 9.]]]])
tensor([[[[False, False, False, False, False,  True, False, False],
          [ True, False,  True, False, False, False, False, False],
          [False, False, False,  True,  True, False, False,  True],
          [False, False, False, False, False, False, False, False],
          [False, 

In [44]:
x = torch.Tensor([[1], [2], [3]])
print ("x.size():",x.size())

y=x.expand( 3,4 )

print ("x.size():",x.size())
print ("y.size():",y.size())

print (x)
print (y)


x.size(): torch.Size([3, 1])
x.size(): torch.Size([3, 1])
y.size(): torch.Size([3, 4])
tensor([[1.],
        [2.],
        [3.]])
tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])


In [75]:
feat = torch.randn([3,3,3])
print(feat)
dim  = feat.size(2)
ind = torch.Tensor([[1,2]]).to(torch.int64)
print(ind)
ind  = ind.unsqueeze(2)
print(ind)
ind = ind.expand(ind.size(0), ind.size(1), dim)
print(ind)
feat = feat.gather(1, ind)

print(feat)

tensor([[[ 0.3317, -0.1337, -1.6714],
         [ 0.2618, -0.0225, -0.1697],
         [ 1.0436, -0.1827,  0.7695]],

        [[ 0.2639,  0.5612, -1.6418],
         [-0.3797,  0.9424,  0.5860],
         [ 2.4738, -1.0252,  0.4398]],

        [[ 0.4882, -1.1817, -0.0117],
         [ 1.0972, -1.4396, -0.8440],
         [ 1.7309, -1.2185,  0.4858]]])
tensor([[1, 2]])
tensor([[[1],
         [2]]])
tensor([[[1, 1, 1],
         [2, 2, 2]]])
tensor([[[ 0.2618, -0.0225, -0.1697],
         [ 1.0436, -0.1827,  0.7695]]])


In [80]:
c = np.empty((0, 5), dtype=int)
print(c)

[]


In [86]:
a = [[1,-2,0,3],[6,-2,-4,0]]
x = np.array(a)
unmatched_a = np.where(x < 0)
print(unmatched_a)

(array([0, 1, 1], dtype=int64), array([1, 1, 2], dtype=int64))


In [5]:
a = np.array([2,3,1])
print(a)

[2 3 1]


In [16]:
from collections import deque

f = deque([],maxlen=3)
f.append(1)
f.append(2)
f.append(3)
f.append(4)
print(f)

deque([2, 3, 4], maxlen=3)


In [17]:
from scipy.spatial.distance import cdist

In [22]:
track_features=np.array([[1,1],[1,2]])
det_features=np.array([[2,1],[2,2],[2,3]])
metric='cosine'
d = cdist(track_features, det_features, metric)
m = np.maximum(0.0,d)
print(track_features)
print(det_features)
print(d)
print(m)
# 

[[1 1]
 [1 2]]
[[2 1]
 [2 2]
 [2 3]]
[[5.13167019e-02 2.22044605e-16 1.94193243e-02]
 [2.00000000e-01 5.13167019e-02 7.72212329e-03]]
[[5.13167019e-02 2.22044605e-16 1.94193243e-02]
 [2.00000000e-01 5.13167019e-02 7.72212329e-03]]
